// Code generated by cmd/generate_setting/main.go. DO NOT EDIT.

package configs

import (
	"github.com/xxcheng123/cloudpan189-share/internal/models"
	"github.com/xxcheng123/cloudpan189-share/internal/shared"
)

// LoadSettingDicts 加载设置字典到 shared 变量
func LoadSettingDicts(dicts []*models.SettingDict) {
	for _, dict := range dicts {
		switch dict.Key {
		case models.SettingDictKeyMultipleStreamThreadCount:
			shared.MultipleStreamThreadCount = dict.Value.Int()
		case models.SettingDictKeyMultipleStreamChunkSize:
			shared.MultipleStreamChunkSize = dict.Value.Int64()
		case models.SettingDictKeyStrmFileEnable:
			shared.StrmFileEnable = dict.Value.Bool()
		case models.SettingDictKeyStrmSupportFileExtList:
			shared.StrmSupportFileExtList = dict.Value.StringSlice()
		case models.SettingDictKeyLinkFileAutoDelete:
			shared.LinkFileAutoDelete = dict.Value.Bool()
		case models.SettingDictKeyStrmBaseURL:
			shared.StrmBaseURL = dict.Value.Value()
		}
	}
}
