// Code generated by cmd/generate_setting/main.go. DO NOT EDIT.

package shared

import "github.com/xxcheng123/cloudpan189-share/internal/models"

var (
	MultipleStreamThreadCount int = models.DefaultMultipleStreamThreadCount
	MultipleStreamChunkSize int64 = models.DefaultMultipleStreamChunkSize
	StrmFileEnable bool = models.DefaultStrmFileEnable
	StrmSupportFileExtList []string = models.DefaultStrmSupportFileExtList
	LinkFileAutoDelete bool = models.DefaultLinkFileAutoDelete
	StrmBaseURL string = models.DefaultStrmBaseURL
)
